package application;

public enum GamePhase {
	PLACE_BOULDER,
	PLACE_MOTHER,
	PLACE_BABY,
	PLACE_INITIAL_SCIENTIST,
	PLACE_REINFORCEMENT_SCIENTIST,
	DISAPPEAR,
	REAPPEAR,
	CARD_SELECT,
	SCIENTIST_CARD,
	SCIENTIST_ACTIONS,
	RAPTOR_CARD,
	RAPTOR_ACTIONS,
	TESTING;
}
